### ISSUE TITLE
Just a thanks

### ISSUE THREAD

**Issue by lulcat** [kni/sml-unicode#1]
Heya.. when there isn't even utf8 in sml one kinda must ask if it's worth learning again etc. This downloaded, compiled seems to work, so just wanted to say a thank you! :)

Will update if something is up or so but I have to rethink project, given languages around the world. This might help though :D

**Comment by kni** [comment]
Thanks. I will update The Unicode Character Database periodically.

**Comment by lulcat** [comment]
Great.. thanks. Looking through it, it's elegant due to concise and 'simple' (loc). Thanks again. 
A small addendum: I am packing this up for you for my distro.. the UCD.pl script you use, I would like to to point to the correct perl lib, but I have only perl unicode. May I ask if it is this https://sourceforge.net/projects/unicore/ or this https://perldoc.perl.org/perlunicode.html project (or another)? 

Also a small typo in a comment  : s/optimazed/optimised/ :p

**Comment by kni** [comment]
Hello.
I beg you - I did not notice your question.
Unicode::UCD is from https://perldoc.perl.org/perlunicode.html and it comes standard with perl.
